# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            exVim
tagline:          ''
description:      ''
url:              http://exvim.github.com

author:
  name:           'exVim Organization'
  url:            http://github.com/exvim

github:
  repo:           https://github.com/exvim/main

# Markup language setup
redcarpet:
  extensions:     [
      "no_intra_emphasis", 
      "fenced_code_blocks", 
      "autolink", 
      "strikethrough", 
      "superscript",
      "tables",
      "with_toc_data",
      "footnotes",
  ]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Navigation
navigation:
- text: Home
  url: /
  layout: index
- text: Downloads
  url: /downloads/
  layout: downloads
- text: Docs
  url: /docs/
  layout: docs
- text: GitHub
  url: https://github.com/exvim/main
- text: Changelog
  url: https://github.com/exvim/main/releases
- text: About
  url: /about/
  layout: index

# User Manual
user_manual:
- text: Intro
  url: /intro/
- text: Install
  url: /install/
- text: Getting Start
  url: /getting-start/
- text: Project Window
  url: /project-window/
- text: Global Search
  url: /global-search/
- text: Config .exvim
  url: /config-exvim/
- text: Config .vimrc
  url: /config-vimrc/
- text: Config Color Scheme
  url: /config-colorscheme/
- text: Plugins
  url: /plugins/
- text: Known Issues
  url: /known-issues/

# Developer Manual
dev_manual:
- text: Select Your Plugin
  url: /select-your-plugin/
