# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            exVim
tagline:          ''
description:      ''
url:              http://exvim.github.com

author:
  name:           'exVim Organization'
  url:            http://github.com/exvim

github:
  repo:           https://github.com/exvim/main

# Markup language setup
redcarpet:
  extensions:     [
      "no_intra_emphasis", 
      "fenced_code_blocks", 
      "autolink", 
      "strikethrough", 
      "superscript",
      "tables",
      "with_toc_data",
  ]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Navigation
navigation:
- text: Home
  url: /
  layout: index
- text: Downloads
  url: /downloads/
  layout: downloads
- text: Docs
  url: /docs/
  layout: docs
- text: GitHub
  url: https://github.com/exvim/main
